// Worker bindings and configuration. `Env` (CHANNEL, APNS_ENABLED) is generated by
// `wrangler types`; the APNs values are secrets and are therefore not in wrangler.jsonc.
export interface RelayEnv extends Env {
  readonly APNS_KEY_ID?: string;
  readonly APNS_TEAM_ID?: string;
  /** ES256 private key in PKCS#8 PEM form (the .p8 file contents). */
  readonly APNS_PRIVATE_KEY?: string;
  /** APNs topic for PushToTalk: `<bundle-id>.voip-ptt`. */
  readonly APNS_TOPIC?: string;
  /** Optional host override, e.g. api.sandbox.push.apple.com. */
  readonly APNS_HOST?: string;
}
